# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Theory and Practice
# theme: slate
remote_theme: pages-themes/slate
# plugins_dir:
# - jekyll-remote-theme # add this line to the plugins list if you already have one
description: > # this means to ignore newlines until "baseurl:"
  My writings about computer science and mathematics and my personal projects therein. 
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
